POST http://localhost:3000/videogames
Content-Type: application/json

{
    "title": "videogame teste",
    "description": "Este é o primeiro videogame á venda de Node.js com MySQL",
    "price": "990.00 R$",
    "games": 1
}
###

GET http://localhost:3000/videogames

###

PUT http://localhost:3000/videogames/b9bfb29f-7981-474c-b989-a293c0c341a5
Content-Type: application/json

{
    "title": "Alterei este videogame",
    "description": "descrição atualizada",
    "price": "1090.00 R$",
    "games": 2
}

###

DELETE  http://localhost:3000/videogames/b298cdc5-6036-43c1-b70d-0453edf4fd27